jlex: license file path fix (WORKDIR -> UNPACKDIR)
* Drop SRC_URI[md5sum]
* Change WORKDIR -> UNPACKDIR where appropriate
* The license file was being looked for in S, it now needs to
  look in UNPACKDIR.

Fixes:
ERROR: jlex-native-1.2.6-r0 do_populate_lic: QA Issue: jlex-native:
LIC_FILES_CHKSUM points to an invalid file:
.../build/tmp/work/x86_64-linux/jlex-native/1.2.6/jlex/jlex-1.2.6-Main.java
[license-checksum]

Signed-off-by: Tim Orling <tim.orling@konsulko.com>